#include "dashboard_endpoint.h"

void registerDashboardEndpoint(AsyncWebServer& server) {
  // Root endpoint - Control dashboard
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
    String html = "<!DOCTYPE html><html><head>";
    html += "<meta charset='UTF-8'>";
    html += "<meta name='viewport' content='width=device-width, initial-scale=1'>";
    html += "<title>VF3 Smart Control</title>";
    html += "<style>";
    html += "body { font-family: Arial; max-width: 600px; margin: 20px auto; padding: 20px; background: #f5f5f5; }";
    html += "h1 { color: #e71e2c; text-align: center; }";
    html += ".section { background: white; padding: 20px; margin: 15px 0; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }";
    html += ".section h2 { margin-top: 0; color: #333; font-size: 18px; border-bottom: 2px solid #e71e2c; padding-bottom: 10px; }";
    html += ".button-group { display: flex; gap: 10px; margin: 10px 0; flex-wrap: wrap; }";
    html += "button { flex: 1; min-width: 120px; padding: 15px; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; transition: all 0.3s; }";
    html += "button:active { transform: scale(0.95); }";
    html += ".btn-primary { background: #e71e2c; color: white; }";
    html += ".btn-primary:hover { background: #c51a26; }";
    html += ".btn-secondary { background: #4CAF50; color: white; }";
    html += ".btn-secondary:hover { background: #45a049; }";
    html += ".btn-warning { background: #ff9800; color: white; }";
    html += ".btn-warning:hover { background: #e68900; }";
    html += ".btn-danger { background: #f44336; color: white; }";
    html += ".btn-danger:hover { background: #da190b; }";
    html += ".status { padding: 10px; background: #f0f0f0; border-radius: 5px; margin: 10px 0; font-family: monospace; font-size: 12px; max-height: 300px; overflow-y: auto; }";
    html += ".status-item { margin: 5px 0; }";
    html += ".message { padding: 10px; margin: 10px 0; border-radius: 5px; text-align: center; display: none; }";
    html += ".message.success { background: #d4edda; color: #155724; display: block; }";
    html += ".message.error { background: #f8d7da; color: #721c24; display: block; }";
    html += "input { width: 100%; padding: 10px; margin: 10px 0; box-sizing: border-box; border: 1px solid #ddd; border-radius: 5px; }";
    html += ".auth-section { background: #fff3e0; border-left: 4px solid #ff9800; }";
    html += ".auth-section input { margin: 5px 0; }";
    html += ".auth-status { padding: 8px; margin: 10px 0; border-radius: 5px; font-size: 14px; text-align: center; }";
    html += ".auth-status.authenticated { background: #d4edda; color: #155724; }";
    html += ".auth-status.not-authenticated { background: #f8d7da; color: #721c24; }";
    html += "</style>";
    html += "</head><body>";
    html += "<h1>\xF0\x9F\x9A\x97 VF3 Smart Control</h1>";

    html += "<div class='section auth-section'>";
    html += "<h2>\xF0\x9F\x94\x91 Authentication</h2>";
    html += "<input type='text' id='apiKeyInput' placeholder='Enter your API Key' value=''>";
    html += "<button class='btn-primary' onclick='setApiKey()' style='width: 100%;'>Save API Key</button>";
    html += "<div id='authStatus' class='auth-status not-authenticated'>Not authenticated - Please enter your API Key</div>";
    html += "</div>";

    html += "<div class='section'>";
    html += "<h2>\xF0\x9F\x94\x90 Lock / Unlock</h2>";
    html += "<div class='button-group'>";
    html += "<button class='btn-primary' onclick='sendCommand(\"/car/lock\", \"POST\")'>\xF0\x9F\x94\x92 Lock Car</button>";
    html += "<button class='btn-secondary' onclick='sendCommand(\"/car/unlock\", \"POST\")'>\xF0\x9F\x94\x93 Unlock Car</button>";
    html += "</div></div>";

    html += "<div class='section'>";
    html += "<h2>\xE2\x9A\xA1 Accessory Power</h2>";
    html += "<div class='button-group'>";
    html += "<button class='btn-secondary' onclick='sendCommand(\"/car/accessory-power\", \"POST\", \"state=on\")'>Power ON</button>";
    html += "<button class='btn-danger' onclick='sendCommand(\"/car/accessory-power\", \"POST\", \"state=off\")'>Power OFF</button>";
    html += "<button class='btn-warning' onclick='sendCommand(\"/car/accessory-power\", \"POST\", \"state=toggle\")'>Toggle</button>";
    html += "</div></div>";

    html += "<div class='section'>";
    html += "<h2>\xF0\x9F\xAA\x9F Windows</h2>";
    html += "<div class='button-group'>";
    html += "<button class='btn-primary' onclick='sendCommand(\"/car/windows/close\", \"POST\")'>Close Windows (30s)</button>";
    html += "<button class='btn-danger' onclick='sendCommand(\"/car/windows/stop\", \"POST\")'>\xE2\x8F\xB9 Stop</button>";
    html += "</div></div>";

    html += "<div class='section'>";
    html += "<h2>\xF0\x9F\x94\x94 Buzzer</h2>";
    html += "<div class='button-group'>";
    html += "<button class='btn-warning' onclick='sendCommand(\"/car/buzzer\", \"POST\", \"state=beep&duration=500\")'>Beep (0.5s)</button>";
    html += "<button class='btn-warning' onclick='sendCommand(\"/car/buzzer\", \"POST\", \"state=beep&duration=1000\")'>Beep (1s)</button>";
    html += "</div></div>";

    html += "<div class='section'>";
    html += "<h2>\xF0\x9F\xAA\x9F Window Down Control</h2>";
    html += "<div class='button-group'>";
    html += "<button class='btn-primary' onclick='sendCommand(\"/car/windows/down\", \"POST\", \"side=left&state=on\")'>\xE2\xAC\x87 Left Down</button>";
    html += "<button class='btn-primary' onclick='sendCommand(\"/car/windows/down\", \"POST\", \"side=right&state=on\")'>\xE2\xAC\x87 Right Down</button>";
    html += "<button class='btn-primary' onclick='sendCommand(\"/car/windows/down\", \"POST\", \"side=both&state=on\")'>\xE2\xAC\x87 Both Down</button>";
    html += "<button class='btn-danger' onclick='sendCommand(\"/car/windows/down\", \"POST\", \"side=both&state=off\")'>Stop All</button>";
    html += "</div></div>";

    html += "<div class='section'>";
    html += "<h2>\xF0\x9F\x93\x8A Car Status</h2>";
    html += "<button class='btn-primary' onclick='getStatus()' style='width: 100%;'>\xF0\x9F\x94\x84 Refresh Status</button>";
    html += "<div class='status' id='status'>Click 'Refresh Status' to load car data...</div>";
    html += "</div>";

    html += "<div class='section'>";
    html += "<h2>\xF0\x9F\x94\xA7 Settings</h2>";
    html += "<button class='btn-warning' onclick='goToReconfigure()' style='width: 100%;'>\xF0\x9F\x94\xA7 Reconfigure Device</button>";
    html += "</div>";

    html += "<div id='message' class='message'></div>";

    html += "<script>";
    html += "function getStoredApiKey() {";
    html += "  return localStorage.getItem('vf3_api_key') || '';";
    html += "}";
    html += "function goToReconfigure() {";
    html += "  const apiKey = getStoredApiKey();";
    html += "  if (!apiKey || apiKey.length < 8) {";
    html += "    showMessage('Please enter your API Key first', true);";
    html += "    return;";
    html += "  }";
    html += "  window.location.href = '/configure?api_key=' + encodeURIComponent(apiKey);";
    html += "}";
    html += "function setApiKey() {";
    html += "  const key = document.getElementById('apiKeyInput').value.trim();";
    html += "  if (key.length < 8) {";
    html += "    showMessage('API Key must be at least 8 characters', true);";
    html += "    return;";
    html += "  }";
    html += "  localStorage.setItem('vf3_api_key', key);";
    html += "  updateAuthStatus();";
    html += "  showMessage('API Key saved successfully!', false);";
    html += "}";
    html += "function updateAuthStatus() {";
    html += "  const key = getStoredApiKey();";
    html += "  const statusEl = document.getElementById('authStatus');";
    html += "  if (key.length >= 8) {";
    html += "    statusEl.textContent = '\xE2\x9C\x85 Authenticated (Key: ' + key.substring(0, 4) + '****)';";
    html += "    statusEl.className = 'auth-status authenticated';";
    html += "  } else {";
    html += "    statusEl.textContent = '\xE2\x9D\x8C Not authenticated - Please enter your API Key';";
    html += "    statusEl.className = 'auth-status not-authenticated';";
    html += "  }";
    html += "}";
    html += "function showMessage(msg, isError) {";
    html += "  const el = document.getElementById('message');";
    html += "  el.textContent = msg;";
    html += "  el.className = 'message ' + (isError ? 'error' : 'success');";
    html += "  setTimeout(() => el.className = 'message', 3000);";
    html += "}";
    html += "function sendCommand(url, method, body) {";
    html += "  const apiKey = getStoredApiKey();";
    html += "  if (!apiKey || apiKey.length < 8) {";
    html += "    showMessage('Please enter your API Key first', true);";
    html += "    return;";
    html += "  }";
    html += "  const options = { method: method, headers: { 'X-API-Key': apiKey } };";
    html += "  if (body) {";
    html += "    options.headers['Content-Type'] = 'application/x-www-form-urlencoded';";
    html += "    options.body = body;";
    html += "  }";
    html += "  fetch(url, options)";
    html += "    .then(r => r.json())";
    html += "    .then(data => {";
    html += "      if (data.success) showMessage(data.message || 'Success!', false);";
    html += "      else showMessage(data.message || 'Failed', true);";
    html += "    })";
    html += "    .catch(e => showMessage('Error: ' + e.message, true));";
    html += "}";
    html += "function getStatus() {";
    html += "  fetch('/car/status')";
    html += "    .then(r => r.json())";
    html += "    .then(data => {";
    html += "      let html = '';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x94\x90 Locks:</strong> ' + (data.controls.car_lock ? '\xF0\x9F\x94\x92 Locked' : '\xF0\x9F\x94\x93 Unlocked') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xE2\x9A\xA1 Accessory Power:</strong> ' + (data.controls.accessory_power ? '\xE2\x9C\x85 ON' : '\xE2\x9D\x8C OFF') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\xAA\x9F Windows:</strong> ' + (data.window_close_active ? '\xE2\x8F\xB3 Closing (' + Math.round(data.window_close_remaining_ms/1000) + 's)' : '\xE2\x9C\x85 Idle') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x9A\xAA Doors:</strong> FL:' + (data.doors.front_left ? '\xF0\x9F\x94\xB4' : '\xF0\x9F\x9F\xA2') + ' FR:' + (data.doors.front_right ? '\xF0\x9F\x94\xB4' : '\xF0\x9F\x9F\xA2') + ' Trunk:' + (data.doors.trunk ? '\xF0\x9F\x94\xB4' : '\xF0\x9F\x9F\xA2') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x92\xA1 Lights:</strong> Demi:' + (data.lights.demi_light ? '\xF0\x9F\x92\xA1' : '\xE2\x9A\xAB') + ' Normal:' + (data.lights.normal_light ? '\xF0\x9F\x92\xA1' : '\xE2\x9A\xAB') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\xAA\x91 Seats:</strong> FL:' + (data.seats.front_left_occupied ? '\xF0\x9F\x91\xA4' : '\xE2\x9A\xAB') + ' FR:' + (data.seats.front_right_occupied ? '\xF0\x9F\x91\xA4' : '\xE2\x9A\xAB') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x94\x97 Seatbelts:</strong> FL:' + (data.seats.front_left_seatbelt ? '\xE2\x9C\x85' : '\xE2\x9A\xA0\xEF\xB8\x8F') + ' FR:' + (data.seats.front_right_seatbelt ? '\xE2\x9C\x85' : '\xE2\x9A\xA0\xEF\xB8\x8F') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x93\xA1 Proximity:</strong> L:' + (data.proximity.rear_left ? '\xF0\x9F\x9A\xA8' : '\xE2\x9C\x85') + ' R:' + (data.proximity.rear_right ? '\xF0\x9F\x9A\xA8' : '\xE2\x9C\x85') + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x9A\x97 Speed:</strong> ' + data.sensors.vehicle_speed + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x8E\xAE Pedals:</strong> Accel:' + data.sensors.accelerator + ' Brake:' + data.sensors.brake + '</div>';";
    html += "      html += '<div class=\"status-item\"><strong>\xF0\x9F\x8E\x9B Steering:</strong> ' + data.sensors.steering_angle + '</div>';";
    html += "      document.getElementById('status').innerHTML = html;";
    html += "    })";
    html += "    .catch(e => showMessage('Error loading status: ' + e.message, true));";
    html += "}";
    html += "window.onload = function() {";
    html += "  const storedKey = getStoredApiKey();";
    html += "  if (storedKey) {";
    html += "    document.getElementById('apiKeyInput').value = storedKey;";
    html += "  }";
    html += "  updateAuthStatus();";
    html += "  getStatus();";
    html += "};";
    html += "</script>";
    html += "</body></html>";
    request->send(200, "text/html", html);
  });
}
